### ISSUE TITLE
Gutenberg

### ISSUE THREAD

**Issue by merijnponzo** [boxybird/wordpress-inertia-plugin#2]
Hi,  any idea how to get this to work with Gutenberg?

Im working with timber and advanced custom fields to load custom blocks, These are Just twig files which can be injected with vue components as well. 

I will give it a try asap :-)

**Comment by boxybird** [comment]
Hello! It works great with Gutenberg content on the frontend. Gutenberg, if using as intended, simply saves HTML markup to the DB. It's basically a fancy WYSIWYG editor.

I love Twig, but InertiaJS (paired with this plugin) is designed to completely replace any WordPress PHP/Twig templating and allow you to use Vue, React, and Svelte instead.

Take this as an example: https://github.com/boxybird/wordpress-inertia-plugin#less-basic

**Comment by merijnponzo** [comment]
I'm really exited to build a first production website in full vue + inertia. 
I can replace my advanced custom field - gutenberg twig blocks with normal php blocks, or maybe render the whole gutenberg content as a json object and then loop trough vue components.

One of the the gutenberg blocks for example is a Tab component, which i certainly want to render with vue. 
Now the tabs + active class are iniated when the dom is ready by jquery 👎 
I can use the $refs within vue... the iniate the tabs on mounted with an active class

Or I guess something like https://www.npmjs.com/package/vue3-runtime-template would be able to render
a vue component (as a string with props) within my gutenberg blocks within the inertia vue page with gutenberg content ;-)
