### ISSUE TITLE
Future releases?

### ISSUE THREAD

**Issue by bedirhandev** [boxybird/wordpress-inertia-plugin#27]
Hello,

Are there going to be any releases in the near future I noticed that in other adapters there are recent commits?

What is your view on this?

Best regards.

**Comment by boxybird** [comment]
Hi, 

There is nothing planned. As WP leans more and more into the Gutenberg editor, I find using this package less valuable.

On top of that, Laravel features are so strong it's hard not to reach for it on new projects.

If I need to use the WP admin for a project, I tend to reach for https://github.com/corcel/corcel.
