### ISSUE TITLE
Blocks

### ISSUE THREAD

**Issue by broskees** [boxybird/wordpress-inertia-plugin#29]
I'm curious if anyone has been able to use this to develop blocks. Experiences?

**Comment by craigrileyuk** [comment]
To develop blocks?

Wouldn't do anything. The adapter works via the template resolution that Wordpress does through the theme on the frontend only.

You could use https://github.com/evo-mark/vite-plugin-gutenberg-blocks

If you mean to display Vue-powered Gutenberg blocks, you'd have to use versions of your framework that allow runtime compilation (e.g. Vue and its `vue.esm-bundler.js` dist).

But there's no reason why not.

**Comment by boxybird** [comment]
This tool passes data from WP to a JS framework of your choice via props. Its use case is for front-end templating only.
